pool: azure-agent

container: mcr.microsoft.com/dotnet/sdk:8.0

variables:
  buildConfiguration: 'Release'

steps:
  - script: dotnet build
    displayName: 'dotnet build $(build Configuration)'
