pool: azure-agent

container: mcr.microsoft.com/dotnet/aspnet:9.0

variables:
  buildConfiguration: 'Release'

steps:
  - script: dotnet build --configuration $(build Configuration)
    displayName: 'dotnet build $(build Configuration)'
